### ISSUE TITLE
Improve Article Card List Design

### ISSUE THREAD

**Issue by RamGoel** [sitern/Lekhak#1]
![Screenshot (52)](https://user-images.githubusercontent.com/71088429/193393125-02c3f9cd-2835-4728-bf2e-246f0dfe8b15.png)

Improve the Design of Cards

**Comment by tanishk-23** [comment]
@RamGoel can you please assign this issue to me?

**Comment by RamGoel** [comment]
@tanishk-23 whats's the update?

**Comment by tanishk-23** [comment]
I have almost done with improving the card list design. Soon I'm gonna make PR.
