### ISSUE TITLE
Feature 👍🏻 : Add Need Help Page

### ISSUE THREAD

**Issue by RamGoel** [sitern/Lekhak#4]
## What to Do?

Make a Page which has FAQ on left and Contact Form on right.

![tedx brochure 1 (1)](https://user-images.githubusercontent.com/80199829/194286143-08624beb-7cd9-4553-8ec8-5bf7488fcdcf.png)

![tedx brochure 1 (1)](https://user-images.githubusercontent.com/90157563/194616489-ab758e77-685b-403d-b2ab-8c0808f994b9.png)

- [ ] Add a EJS page in views directory and write code for UI in that file.
- [ ] Add route for that page in index.js

**Comment by fosa-ij** [comment]
Hi, concerning this issue, do you already have the contents/vital information of the need help page or am I to come up with one?

**Comment by KGoutham7214** [comment]
Hi please check out the pr i opened on this issue

**Comment by RamGoel** [comment]
> Hi, concerning this issue, do you already have the contents/vital information of the need help page or am I to come up with one?

Hi @fosa-ij ,thanks for showing interest. You have to come up with your own design and information but try to keep it sync with other pages.

**Comment by fosa-ij** [comment]
Ok sure thing.
Thanks 👍

**Comment by fosa-ij** [comment]
Hi @RamGoel please check out the pull request I made on this issue

**Comment by KGoutham7214** [comment]
you could have merged any one pull request atleast for hacktoberfest score
